version: "3"
services:
  web:
    env_file:
        - .env
    build: .
    command: python app.py
    ports:
        - $PORT:$PORT
    volumes:
        - .:/app
volumes:
    apidata:
      driver: local